# ***IS Ai helpful For Students or Cheater ?***

### 1. ***Import Library Thats used for working on this data***

In [1]:
import pandas as pd

### 2. ***Load Data Set***

In [2]:
df=pd.read_csv("ai_student_impact_dataset.csv")

### 3. ***Check Shape of Your Data***

In [3]:
print("Shape of Data : ",df.shape)

Shape of Data :  (50000, 16)

### 4. ***Quick Overview***

In [4]:
df.head() #First Five rows
df.tail() #Last Five rows

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

### ***Data Cleaning and Preprocessing(Prepare data for model)***
***The dataset contains various features that range from numerical scores to categorical information about AI usage. We check for missing values, data types, and any inconsistencies that could affect our analysis. In this step, we also convert the boolean column and set appropriate types where possible.***

In [5]:
df["Paid_Subscription"].astype

<bound method NDFrame.astype of 0         True
1        False
2        False
3        False
4        False
         ...
49995    False
49996    False
49997     True
49998    False
49999    False
Name: Paid_Subscription, Length: 50000, dtype: bool>

In [6]:
# Check for missing values
missing_vals = df.isnull().sum()
print('Missing values in each column:')
print(missing_vals)

#Make year of study category
df["Year_of_Study"]=df["Year_of_Study"].astype("category")

# Quick Check of Each Column DAta type
print("\nDataTypes: ")
print(df.dtypes)

Missing values in each column:
Student_ID                    0
Major_Category                0
Year_of_Study                 0
Pre_Semester_GPA              0
Weekly_GenAI_Hours            0
Primary_Use_Case              0
Prompt_Engineering_Skill      0
Tool_Diversity                0
Paid_Subscription             0
Traditional_Study_Hours       0
Perceived_AI_Dependency       0
Institutional_Policy          0
Anxiety_Level_During_Exams    0
Post_Semester_GPA             0
Skill_Retention_Score         0
Burnout_Risk_Level            0
dtype: int64

DataTypes:
Student_ID                       int64
Major_Category                  object
Year_of_Study                 category
Pre_Semester_GPA               float64
Weekly_GenAI_Hours             float64
Primary_Use_Case                object
Prompt_Engineering_Skill        object
Tool_Diversity                   int64
Paid_Subscription                 bool
Traditional_Study_Hours        float64
Perceived_AI_Dependency          int64
Institutional_Policy            object
Anxiety_Level_During_Exams       int64
Post_Semester_GPA              float64
Skill_Retention_Score          float64
Burnout_Risk_Level              object
dtype: object

### 4. ***Analysis***

In [12]:
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [19]:
df['GPA_Change'] = df['Post_Semester_GPA'] - df['Pre_Semester_GPA']
df

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level,GPA_Change
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High,-0.025
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low,-0.125
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium,0.101
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium,0.211
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium,0.163
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High,0.685
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium,0.226
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High,0.428
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium,0.129
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low,0.019

In [20]:
df.groupby('Perceived_AI_Dependency')['GPA_Change'].mean()

Perceived_AI_Dependency
1     0.202674
2     0.204884
3     0.210171
4     0.208057
5     0.207944
6     0.196108
7     0.168888
8     0.160255
9     0.135233
10    0.108079
Name: GPA_Change, dtype: float64

In [21]:
df.groupby('Perceived_AI_Dependency')['Skill_Retention_Score'].mean()

Perceived_AI_Dependency
1     75.997832
2     76.477936
3     76.483281
4     76.354022
5     75.851789
6     74.901460
7     72.471852
8     69.400339
9     65.555582
10    63.547474
Name: Skill_Retention_Score, dtype: float64

In [22]:
df.groupby('Perceived_AI_Dependency')['Anxiety_Level_During_Exams'].mean()

Perceived_AI_Dependency
1     3.423388
2     3.741492
3     4.068334
4     4.390779
5     4.782061
6     5.187447
7     5.610337
8     6.042105
9     6.423280
10    6.915789
Name: Anxiety_Level_During_Exams, dtype: float64

# 5. ***Conclusion***

The data shows that AI can either help or harm students — it depends on **how much** they use it.

- **Low to Moderate AI use (levels 1–5):** Students in this group have the **best GPA improvement** and their **skill retention stays high (~76)**. This means AI is genuinely helping them study better without replacing their own learning.

- **High AI use (levels 7–10):** Students here show a clear drop in outcomes:
  - GPA improvement becomes smaller
  - **Skill retention falls sharply (down to ~63–65)** — showing they are just getting answers instead of actually learning
  - **Exam anxiety increases**
  - **Burnout risk jumps drastically** (95% high burnout at max dependency vs only 10% at low dependency)

**Takeaway:** Used in moderation, AI acts like a helpful study assistant — it saves time and slightly boosts performance without hurting understanding. But when students over-rely on AI, it starts behaving like a shortcut for cheating — grades stop improving, real skills disappear, and stress/burnout go up.

So the answer to *"Is AI helping students or making them cheaters?"* is: **it's helpful in moderation, but harmful in excess.**