In [3]:
import pandas as pd

In [4]:
import numpy as np

![Data Science Flow](Screenshot.png)

***
- EDA(2)
- Linkhttps://drive.google.com/drive/folders/1-eTqjsc0S331v8VFazbQQC2CNZeRcbdI
- ![EDA Explanantion](EDA.png)

***
Intro To Pandas
- Link https://drive.google.com/drive/folders/1-eTqjsc0S331v8VFazbQQC2CNZeRcbdI

In [5]:
info={
    "Name":["rahul","Harshita","shardah"],
    "Marks":[9.5,7.5,8.5]
}

df=pd.DataFrame(info)
df

       Name  Marks
0     rahul    9.5
1  Harshita    7.5
2   shardah    8.5

***
Series(1d labeld Array)

- Link https://drive.google.com/drive/folders/1-eTqjsc0S331v8VFazbQQC2CNZeRcbdI

In [6]:
# Series In pandas
s=pd.Series([11,22,33])
print(s)

# Indexing
print(s[0]) #print 11
print(s[2]) #print 33

print(s.index) #All albels

#Custom Indexing
s=pd.Series([23,12,56,12], index=["Adam", "Eve", "Charlie", "Bob"])
print(s["Eve"]) #12
print(s["Bob"]) #12

0    11
1    22
2    33
dtype: int64
11
33
RangeIndex(start=0, stop=3, step=1)
12
12

***
Series Properties
- link https://drive.google.com/drive/folders/1-eTqjsc0S331v8VFazbQQC2CNZeRcbdI
- ![Series Properties](Series_Properties.png)

In [7]:
# Vectorization Operations
s1=pd.Series([1,2,3])
s2=pd.Series([4,5,6])
print(s1+s2)

# Mutable values but immutable Size
s3=pd.Series([2,3,4])
print(s3)
s3[0]=100
print(s3)

changed_s = s3.drop(1)
print(changed_s)
print(s3)

0    5
1    7
2    9
dtype: int64
0    2
1    3
2    4
dtype: int64
0    100
1      3
2      4
dtype: int64
0    100
2      4
dtype: int64
0    100
1      3
2      4
dtype: int64

*** Data Frames in Pandas(2d labeled Array)
- Link https://drive.google.com/drive/folders/1-eTqjsc0S331v8VFazbQQC2CNZeRcbdI

In [8]:
# DataFrame in pandas - using dictionary
info = {
    "Name" : ["Adam", "Eve", "Bob"],
    "Marks" : [78, 99, 85],
    "Grade" : ['B', 'O', 'A']
}
df=pd.DataFrame(info)
print(df)

print(df.index)        # row labels
print(df.columns)      # column labels

# DataFrom using Numpy array
numpy_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
df1=pd.DataFrame(numpy_array,columns=["A","B","C"])
print(df1)

# DataFrom using Lists
l = [["Adam", 96], ["Eve", 75], ["Bob", 82], ["Charlie", 92]]
df3=pd.DataFrame(l,columns=["Name", "Marks"])
print(df3)

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Grade'], dtype='object')
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
      Name  Marks
0     Adam     96
1      Eve     75
2      Bob     82
3  Charlie     92

***
Read the data
- Link https://drive.google.com/drive/folders/1-eTqjsc0S331v8VFazbQQC2CNZeRcbdI

In [9]:
df=pd.read_csv("employee_data.csv")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [10]:
# DataFrame Methods
df = pd.read_csv("employee_data.csv")

print(df.head()) # 1st 5 rows of whole data
print(df.head(7)) # Give 7 1st rows of data


print(df.tail()) # gives last 5 rows
print(df.tail(2)) # Gives only 2 last rows of data

print(df.shape) #(Rows,columns)

print(df.columns) # Gives all columns name
print(df.index)  #overview of indexes Numbers

print(df.describe()) # Explai your whole data 


print(df.info()) #tells about columns ,null values,types of eac row,

print(df.nunique()) # tells unique values in every column

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000
   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000
(10, 5)
Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')
RangeIndex(start=0, stop=10, step=1)
             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes
None
ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [11]:
df=pd.read_csv("globalAirQuality.csv")
print(df)

                        timestamp country      city  latitude  longitude  \
0      2025-11-04 18:25:17.554219      US  New York    40.713    -74.006
1      2025-11-04 19:25:17.554219      US  New York    40.713    -74.006
2      2025-11-04 20:25:17.554219      US  New York    40.713    -74.006
3      2025-11-04 21:25:17.554219      US  New York    40.713    -74.006
4      2025-11-04 22:25:17.554219      US  New York    40.713    -74.006
...                           ...     ...       ...       ...        ...
17995  2025-11-19 13:25:17.554219      CH    Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH    Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH    Zurich    47.377      8.542
17998  2025-11-19 16:25:17.554219      CH    Zurich    47.377      8.542
17999  2025-11-19 17:25:17.554219      CH    Zurich    47.377      8.542

         pm25     pm10     no2    so2      o3     co  aqi  temperature  \
0      50.295  108.938  27.998  6.539  52.568  1.096  108       18.504
1      32.083   63.043  36.120  4.021  43.536  1.075   90        5.838
2      42.250   82.553  26.935  9.538  23.320  0.977   84       31.833
3      30.403   79.951  63.536  7.609  31.369  0.230  158       23.140
4      21.083   66.423  38.997  6.919  45.615  1.085   97       13.632
...       ...      ...     ...    ...     ...    ...  ...          ...
17995  27.899   74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950   47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347   72.908  46.976  5.763  66.492  0.947  122       21.951
17998  40.722   95.152  32.957  5.524  53.193  0.868   95       24.042
17999  25.830   30.411  35.317  4.336  66.246  0.848   88        8.529

       humidity  wind_speed
0        70.168       3.725
1        80.088       8.969
2        62.783       9.650
3        89.153       8.956
4        76.499       4.017
...         ...         ...
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660
17998    31.880       2.642
17999    59.104       4.403

[18000 rows x 15 columns]

In [12]:
print(df.head())

                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083
2  2025-11-04 20:25:17.554219      US  New York    40.713    -74.006  42.250
3  2025-11-04 21:25:17.554219      US  New York    40.713    -74.006  30.403
4  2025-11-04 22:25:17.554219      US  New York    40.713    -74.006  21.083

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088
2   82.553  26.935  9.538  23.320  0.977   84       31.833    62.783
3   79.951  63.536  7.609  31.369  0.230  158       23.140    89.153
4   66.423  38.997  6.919  45.615  1.085   97       13.632    76.499

   wind_speed
0       3.725
1       8.969
2       9.650
3       8.956
4       4.017

In [13]:
# Selecting Data

# Select columns
df["country"]
df[["city", "aqi"]]

# Select rows (by label)
df.loc[0]             # 1st row (by label)
df.loc[0:3]           # row0 to row3 - both inclusive in loc

# Select rows (by index)
df.iloc[0]            # 1st row 
df.iloc[4:7]          # 1st row 

# Select rows & columns
df.loc[0, "country"]  # 0th row & specific column
df.iloc[0, 2]         # 1th row & 3rd column (by position)

df.iloc[0, 1:5]
df.loc[0, ["country", "aqi"]]

df.loc[0:5, ["country", "city", "latitude"]]   # end is inclusive
df.iloc[0:5, 1:3]                              # end is exclusive 

# Select single scalar value
df.at[0, "city"]
df.iat[0, 2]

'New York'

In [14]:
# Filtering Data
df[df["aqi"] > 100]
df[df["aqi"] > 100][["city", "aqi"]]

df[(df["aqi"] > 100) & (df["timestamp"] == "2025-11-04 18:25:17.554219")]
aqi_data = df[(df["aqi"] > 100) & (df["timestamp"] == "2025-11-04 18:25:17.554219")][["city", "aqi"]]

# Difference in loc & iloc - both give same value
aqi_data.loc[360] 
aqi_data.iloc[1]

# Query - returns a copy, not a view
df.query("aqi > 100 & timestamp == '2025-11-04 18:25:17.554219'")

my_country = "IN"
df.query("country == @my_country")

df["timestamp"] = pd.to_datetime(df["timestamp"])
df["date"] = df["timestamp"].dt.date
selected_date = pd.to_datetime("2025-11-04").date()

df.query("country == @my_country & date == @selected_date & aqi > 100")

# Use .copy() to avoid confusion
countries = df[["country", "aqi"]].copy()
countries.loc[0:4, "country"] = "India"

print(countries)

      country  aqi
0       India  108
1       India   90
2       India   84
3       India  158
4       India   97
...       ...  ...
17995      CH  103
17996      CH  105
17997      CH  122
17998      CH   95
17999      CH   88

[18000 rows x 2 columns]

In [15]:
# Cleaning Data
df = pd.read_csv("raw_data (1).csv") 
print(df)

df.isnull() # True for null values (NaN)
df.isna()    # True for null values (NaN)

df.isnull().sum() # Count missing values

df.dropna()            # drops rows with missing values
df.dropna(axis = 1)    # drops cols with missing values

df

df.fillna(0)           # fills NaN with value
df["age"] = df["age"].fillna(df["age"].mean())           # fills column with mean

df.ffill() #Forward fill
df.bfill() #Backword fill

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  51000.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6    Ahmed Khan  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     USA     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [16]:
# Handle Duplicate values
df = pd.read_csv("raw_data (1).csv") 

df.duplicated()                      # True for duplicate rows
df.duplicated("country")             # True for duplicate rows in particular col
df.duplicated(["country", "gender"]) 

df.drop_duplicates()                 # drops duplicate rows

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [17]:
# Handle Data Types
df = pd.read_csv("raw_data (1).csv") 

df.dtypes                                     # dtype of each col
df2 = df.fillna(0).copy()
df2["income"] = df2["income"].astype(int)       # change dtype

# String type
df2["gender"].str.lower()                      # lower case
df2["gender"].str.upper()                      # upper case
df2["gender"].str.capitalize()                 # capitalize

df2["gender"].str.capitalize()                 # capitalize
df2["name"].str.split(" ")                     # splits into lists based on separator value 
type(df2["name"].str.split(" ")[0])            

df2["country"].str.contains("US")
df2["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

***Transformation , Feature Engineering***

In [32]:
df=pd.read_csv("raw_data (1).csv")
df

#Make a copy
df2=df.copy()

# .apply()
# apply a fnx to a row or col
df2["tax"]=df2["income"].apply([lambda x:"10%" if x<60000 else "20%"])
df2

#maping
# map values to another
new_gender_vals = {"Male": "M", "Female": "F", "Unknown": "U"}
df2["gender"]=df2["gender"].map(new_gender_vals)
df2

#.assign(argument)
# assign some new values
df2.assign(new_income=df2["income"]*1.1)

#.replace()
# replace specific values
df2["country"].replace("USA","United state")

0     United state
1     United state
2           Canada
3     United state
4            Spain
5            China
6            India
7              NaN
8     United state
9           Mexico
10    United state
Name: country, dtype: object

In [23]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [33]:
# Transformation - Sorting
df2 = df.copy()

# Renaming
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income"]
df2.rename(columns={"Income": "Salary"})
df2.rename(index={0: "first"})

# Sorting - values & index
df2.sort_values("Income")                     # sort values in ascending
df2.sort_values("Income", ascending=False)    # sort values in descending
df2.sort_values(["Age", "Income"])            # sorts for age, if age is same then sorts for income 

sorted_df2 = df2.sort_values(["Age", "Income"])
sorted_df2.sort_index()

# Reset Index
sorted_df2.reset_index()
sorted_df2.reset_index(drop=True)     # to drop original index vals

# Ranking
df2["Ranking"] = df2["Income"].rank(ascending=False, method="dense")

# Reorder
df2[["Id", "Name", "Age", "Income", "Gender", "Country", "Ranking"]]

    Id          Name   Age   Income   Gender Country  Ranking
0    1      John Doe  29.0  55000.0     Male     USA      5.0
1    1      John Doe  29.0  55000.0     Male     USA      5.0
2    2    Jane Smith   NaN  62000.0   Female  Canada      3.0
3    3          Alex   NaN  47000.0  Unknown     USA      7.0
4    4  Maria Garcia  34.0      NaN   Female   Spain      NaN
5    5        Li Wei  27.0  51000.0     Male   China      6.0
6    6           NaN  45.0  73000.0   Female   India      1.0
7    7    Ahmed Khan  38.0  68000.0     Male     NaN      2.0
8    8    Rachel Lee  29.0  62000.0   Female     USA      3.0
9    9   Carlos Ruiz   NaN  45000.0     Male  Mexico      8.0
10  10   Emily Davis  31.0  58000.0      NaN     USA      4.0

In [34]:
# Grouping & Aggregation
df2 = df.copy()

df2.groupby("country")["income"].mean()     # mean income for each country
df2.groupby("gender")["income"].mean()      # mean income for each gender

df2.groupby("country")["gender"].count()       # count of gender for each country
df2.groupby("gender")["income"].max()       # max income for each gender

df2.groupby("country")["income"].agg(["mean", "min", "max"])         # applies multiple aggregate functions
df2.groupby("country")["income"].aggregate(["mean", "min", "max"])   # alias

df2.groupby("country")["income"].agg(avg_salary="mean", max_salary="max")   # rename aggregate

df2.groupby("country").agg({
    "age": "mean",
    "income": "mean"
})   # aggregate on multiple cols

df2.groupby("country").agg(
    avg_age=("age", "mean"),
    avg_salary=("income", "mean")
)   # rename aggregates on multiple cols

         avg_age  avg_salary
country
Canada       NaN     62000.0
China       27.0     51000.0
India       45.0     73000.0
Mexico       NaN     45000.0
Spain       34.0         NaN
USA         29.5     55400.0

In [35]:
# Melt & Pivot
df = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22]
})

melted = df.melt(
    id_vars=["country", "year"],     # columns to keep
    value_vars=["sales", "profit"],  # columns to unpivot
    var_name="metric",               # new column name for variable
    value_name="value (in Lakhs)"    # new column name for value (default is value)
)

print(melted)

original = melted.pivot(
    index=["country", "year"],   # cols that become the NEW row index - can't for just country
    columns="metric",            # col whose unique values will become the cols
    values="value (in Lakhs)"    # col whose values will fill the new df
)

print(pivoted)

  country  year  metric  value (in Lakhs)
0     USA  2020   sales               100
1     USA  2021   sales               120
2   India  2020   sales                90
3   India  2021   sales               110
4     USA  2020  profit                20
5     USA  2021  profit                25
6   India  2020  profit                18
7   India  2021  profit                22

NameError: name 'pivoted' is not defined

In [36]:
# Concatenation
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Adam", "Bob", "Charlie"]
})

df2 = pd.DataFrame({
    "id": [4, 5, 6],
    "name": ["David", "Eva", "Frank"]
})

pd.concat([df1, df2])                       # Row wise concatenation
pd.concat([df1, df2], axis=1)               # Col wise concatenation
pd.concat([df1, df2], ignore_index=True)    # Row wise concatenation - new index

   id     name
0   1     Adam
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eva
5   6    Frank

In [37]:
# Merging & Joining
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

pd.merge(df_customers, df_orders, on="customer_id")                  # Inner Join
pd.merge(df_customers, df_orders, on="customer_id", how="left")      # Left Join
pd.merge(df_customers, df_orders, on="customer_id", how="right")     # Right Join
pd.merge(df_customers, df_orders, on="customer_id", how="outer")     # Outer Join

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [38]:
# Concatenation
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Adam", "Bob", "Charlie"]
})

df2 = pd.DataFrame({
    "id": [4, 5, 6],
    "name": ["David", "Eva", "Frank"]
})

pd.concat([df1, df2])                       # Row wise concatenation
pd.concat([df1, df2], axis=1)               # Col wise concatenation
pd.concat([df1, df2], ignore_index=True)    # Row wise concatenation - new index

   id     name
0   1     Adam
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eva
5   6    Frank

In [39]:
# Basic Visualization

df["age"].hist()
df.plot(kind='scatter', x='age', y='income')

KeyError: 'age'